# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ec2a221edeb87ea35430b8444d1972858d6e564150836944992221157d8745855d166585f00a1a7da1d6e25a8e791e5fb116fdb61a634fd7a4d697dd9a7e6ee9

test:
  secret_key_base: 8f5eeffa67afdcf893eff4e44bfe13cd619bd84e63510d73f4b4da4229acb53382d1e049ee8b59f0d6d5de1e972eb0e98d27ca5fae7d2aead37b0542296565f4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
